version: '3.8'
services:
  db:
    image: postgres:12.3
    container_name: postgres
    ports:
    - 5432:5432
    volumes:
    - ../pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: docker_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    build: .
    command: python manage.py runserver 0:8000
    container_name: application
    ports:
    - 8000:8000
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db

